version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./:/var/lib/rabbitmq/
      - ./:/var/log/rabbitmq

  psqldb:
    image: postgres:13
    container_name: psqldb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - psqldb:/var/lib/postgresql/
volumes:
  psqldb:
networks:
  tekana-net:
